### ISSUE TITLE
not necessarily an issue, but do you know how i would fix this error?

### ISSUE THREAD

**Issue by TheSnazzmaster** [ozelot379/ConvertJavaTextureToBedrock#13]
![image](https://user-images.githubusercontent.com/43121657/86554715-40220580-bf03-11ea-8428-82df5de8edee.png)

**Comment by ozelot379** [comment]
@TheSnazzmaster
Such errors occur, if the converter pass an area of an image to the used [Jimp library](https://github.com/oliver-moran/jimp) which is outside of width/height

According to your screenshot it seems to be the particle sprite

You can try to delete the particle folder (`assets/minecraft/textures/particle`) in the Java texture pack to skip this conversion

Unfortunately I can't analyse more precisely, because I dont't have the texture pack that you used to convert

But if you want to convert the particle, may it help you the follow for analyse it yourself in the source code:
The error should occur somewhere [here](https://github.com/ozelot379/ConvertJavaTextureToBedrockApi/blob/934b107edf593ee07969c704638994e1725eac3a/src/converter/SpriteConverter.mjs#L45-L48) and [here](https://github.com/ozelot379/ConvertJavaTextureToBedrockApi/blob/934b107edf593ee07969c704638994e1725eac3a/src/converter/SpriteConverter.mjs#L155-L257) are the construction of the particle sprite image
