### ISSUE TITLE
Horse textures aren't mapped properly

### ISSUE THREAD

**Issue by rtm516** [ozelot379/ConvertJavaTextureToBedrock#22]
**Describe the issue**
Horse textures aren't mapped properly

Java:
![image](https://user-images.githubusercontent.com/5401186/96052294-220a6080-0e75-11eb-88f6-452df4aa99ed.png)

Bedrock:
![image](https://user-images.githubusercontent.com/5401186/96052352-46fed380-0e75-11eb-925c-ddb9acc2f473.png)

**System info**

***Converting***
System OS: Windows 10 1909
Browser: Chrome 86

***Game***
System OS: Windows 10 1909
Version: 1.16.40

**Texture pack**
Link to download: https://faithful.team/faithful-1-16-3/

**Comment by ozelot379** [comment]
@rtm516
Convert of horses are now exprimental in v4.1.0
I think it's not possible to convert completely correctly from Java to Bedrock, because it's a complete different texture, not only different arranged positions
If you should find a solution in GeyserMC/PackConverter, feel free for let it me know, so I can improve it in this converter too ...
