### ISSUE TITLE
Converts almost nothing

### ISSUE THREAD

**Issue by Obydux** [ozelot379/ConvertJavaTextureToBedrock#26]
**Describe the issue**

A clear and concise description of what the issue is.
When i try to convert this resource pack to bedrock it almost doesn't convert anything and goes from a 1.7MB .zip to a 614B .mcpack

Is there an error message?
No
Which step is previous the error message?

Is it the same error/step or is different if you try multiple times?

Are the textures available/correct on Java version?
Yes
**System info**

***Converting***
System OS: Linux Mint 20
Browser: Firefox

***Game***
System OS: Android 10

**Texture pack**
(optimal, but on advantage, so that issues can be analyzed and fixed more precisely)
[resource2.zip](https://github.com/ozelot379/ConvertJavaTextureToBedrock/files/5451111/resource2.zip)
Link to download: https://resourcepack.host/dl/YYyNJZuVbg28L78VZqSHrEW7cS1qgH9x/resource2.zip

**Comment by ozelot379** [comment]
@Obydux

Custom models are not supported, which this texture pack is using

The size diffirent is because the converter will remove all other files in `assets` except `assets/minecraft/textures` and `assets/minecraft/sounds/` for speed up loading

In this texture pack there is no `assets/minecraft/textures` because custom models, so just the metadata file remains
