### ISSUE TITLE
Converter doesnt rearrange the phantom entity file

### ISSUE THREAD

**Issue by FoxMcCloudl** [ozelot379/ConvertJavaTextureToBedrock#29]
As the title says the converter doesnt seem to rearrange the phantom entity file before converting and saving as .tga. There is not any error messages about the phantom when converting. The Phantom texture does work in Java without Optifine.

**System info**
Windows 10 Pro 64bit
32GB RAM
R5 2600 CPU
RTX 2080

***Converting***
System OS: Windows 10 Pro 64bit
Browser: Firefox

***Game***
System OS: Windows 10 Pro 64bit

**Texture pack**
Link to download: https://www.curseforge.com/minecraft/texture-packs/lb-photo-realism-reload/download/3106932

**Comment by ozelot379** [comment]
@FoxMcCloudl

The arrangement of the `phantom.png` entity file is the same in Java and Bedrock version, that is not the problem

In Java there is a second entity file `phantom_eyes.png` for the eyes, in Bedrock, there is only one file (The alpha of the eyes are set to transparent for differ)

Because the texture pack is using no transparent area in `phantom_eyes.png` but using black colors, the converter can not be different the main part between eyes part and will take only the eyes part and override the main part with black colors

You can either delete `/textures/entity/phantom.tga` from the output for use the default Bedrock texture or manual edit `/assets/minecraft/textures/entity/phantom_eyes.png` from input by replace black part with transparent part before converting

For instance in `GIMP`, you can use `Fuzzy Select Tool`, click on the black area and press `Delete` key on your keyboard, but I think, other image programs can this too, if you use an other
