### ISSUE TITLE
chroma hills

### ISSUE THREAD

**Issue by shihadaman** [ozelot379/ConvertJavaTextureToBedrock#6]
**Describe the issue**
A clear and concise description of what the issue is.

**System info**
System OS: android
Browser: mozilla firefox

**Texture pack**
(optimal, but on advantage, so that issues can be analyzed and fixed more precisely)
Link to download:chromahills.com 

"chromahills" texture pack when  i try to convert in the end it says ( ERROR: uncaught exception: out of memory )

**Comment by shihadaman** [comment]
Fix it if you can plz

**Comment by ozelot379** [comment]
@shihadaman 
I think, the error means that your device has too little memory to convert this HD texture pack

I don't know I can do something, because this web app takes the whole extracted texture pack in the users memory, convert, pack and deliver to download, all from there

Which step is previous the error? The same or vary it if you try multiple?

You could try to close other apps than the web browser or reboot your device or disable experimental features if you enabled it

It works on my available devices
